### ISSUE TITLE
why not use atob and btoa?

### ISSUE THREAD

**Issue by coolaj86** [beatgammit/base64-js#12]
I'm just curious on this one. Is there a js environment that doesn't implement that?

**Comment by coolaj86** [comment]
ooops, didn't see the thing about the byte array. pretend I didn't say anything

**Comment by Quiark** [comment]
Web Worker in Safari 8 doesn't have it.

**Comment by oliverjanik** [comment]
Also it chokes on non ASCII characters. In other words those functions are completely broken.

https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding
