### ISSUE TITLE
Bower Registration via git tag

### ISSUE THREAD

**Issue by coolaj86** [beatgammit/base64-js#15]
I already ran this

```
bower register base64-js https://github.com/beatgammit/base64-js
```

But you need to accept the pull request and also you'll need to run

```
git clone git@github.com:beatgammit/base64-js.git
pushd base64-js
git tag v1.0.0
git push --tags
```

**Comment by beatgammit** [comment]
Alright, it's done.

**Comment by beatgammit** [comment]
I've added you as a collaborator, so feel free to make changes as necessary.

**Comment by coolaj86** [comment]
![](http://www.quickmeme.com/img/da/da1fa76353cd16b1df0627cd92cf9b8f03e5890b95b234c6c3a268214587b20e.jpg)
