### ISSUE TITLE
Number of object allocations and function calls

### ISSUE THREAD

**Issue by myitcv** [beatgammit/base64-js#20]
Hi - looking to pick up and use this library if possible because we are looking to massively optimise this part of our code.

However I have a question about the number of object allocations and function calls that are made in a call to either `toByteArray` or `fromByteArray`

Consider the following Base64 string (taken from [here](https://en.wikipedia.org/wiki/Base64)):

```
let s = "TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCBieSB0aGlzIHNpbmd1bGFyIHBhc3Npb24gZnJvbSBvdGhlciBhbmltYWxzLCB3aGljaCBpcyBhIGx1c3Qgb2YgdGhlIG1pbmQsIHRoYXQgYnkgYSBwZXJzZXZlcmFuY2Ugb2YgZGVsaWdodCBpbiB0aGUgY29udGludWVkIGFuZCBpbmRlZmF0aWdhYmxlIGdlbmVyYXRpb24gb2Yga25vd2xlZGdlLCBleGNlZWRzIHRoZSBzaG9ydCB2ZWhlbWVuY2Ugb2YgYW55IGNhcm5hbCBwbGVhc3VyZS4=";
```

A call to `base64.toByteArray` results in 629 function calls.

Calling `base64.fromByteArray` on the result of the previous call results in 450 function calls.

Unless one's Javascript runtime is inlining all of these function calls there is going to be an overhead for each one (I'm not sure to what extent Javascript VMs have evolved...?)

`encode` for example is called 360 times; this is simply accessing an object. 

Many of these calls could simply be inlined 'by hand' so as not to rely on the Javascript VM (which may vary between browsers etc)

Has this been explored at all?

Are there any performance tests which would help to benchmark the significance of any such changes?

Thanks

**Comment by feross** [comment]
There is a benchmark file [here](https://github.com/beatgammit/base64-js/blob/master/bench/bench.js) that you can use to figure out if your changes would have any effect.

My guess is that most modern JS engines will optimize and inline this code if it's hot in your application.

If you send a PR to inline `encode()` I'll merge that right away, since I agree it's kind of silly.

**Comment by myitcv** [comment]
Thanks for the response. If I were pulling together a PR, I would simply inline all of them - this library is simple enough and you have the added benefit that you then then don't need to rely on a VM implementation.

I've switched to using the Google Closure library function in the meantime. I'll leave it up to you if you want to keep this issue open for tracking purposes.

**Comment by feross** [comment]
I looked into this a bit more and managed to improve things quite a bit!

Before:
```
decode ms, decode ops/ms, encode ms, encode ops/ms
21 63492.19047619047 35 38095.31428571429
base64.toByteArray() (decode) x 52.89 ops/sec ±1.77% (62 runs sampled)
base64.fromByteArray() (encode) x 38.70 ops/sec ±2.38% (49 runs sampled)
```

After:
```
decode ms, decode ops/ms, encode ms, encode ops/ms
10 133333.6 40 33333.4
base64.toByteArray() (decode) x 166 ops/sec ±1.65% (66 runs sampled)
base64.fromByteArray() (encode) x 38.98 ops/sec ±2.47% (48 runs sampled)
```

Decoding is 3 times faster after the changes.

**Comment by myitcv** [comment]
Looks good.

**Comment by feross** [comment]
1.1.0
