### ISSUE TITLE
Unable to use lib in browser since #21

### ISSUE THREAD

**Issue by mttcr** [beatgammit/base64-js#22]
Hello,
Quoting the comment of the commit : 

> if folks miss the ability to drop this into the browser, open an issue and we’ll add a built file to the repo

What was the main reason to remove the self executing function, which prevents adding variables to the global scope ? Should we encapsulate the file in a function to use it in a browser ?

**Comment by feross** [comment]
This is fixed in 1.1.1. Going forward, you should use the `base64js.min.js` file in the root of the repo. This file supports all possible environments you might use it in, because it uses [UMD](https://github.com/umdjs/umd).

Cheers, and sorry for the temporary trouble!
