### ISSUE TITLE
Version out of date in bower.json

### ISSUE THREAD

**Issue by mroch** [beatgammit/base64-js#26]
Looks like the version in bower.json is still 1.0.0, which causes this warning when installing:

```
$ bower install --save base64-js
bower base64-js#*           not-cached https://github.com/beatgammit/base64-js.git#*
bower base64-js#*              resolve https://github.com/beatgammit/base64-js.git#*
bower base64-js#*             checkout v1.1.2
bower base64-js#*             mismatch Version declared in the json (1.0.0) is different than the resolved one (1.1.2)
bower base64-js#*             resolved https://github.com/beatgammit/base64-js.git#1.1.2
bower base64-js#^1.1.2         install base64-js#1.1.2
```

**Comment by feross** [comment]
This is why bower.json was an unfortunate decision. No one remembers to keep it up to date. Will remove bower.json and see if that makes the warning go away.

**Comment by Amndeep7** [comment]
I installed this just now, and the bower.json file was downloaded with the repo, and is still incorrect in regards to version number.

**Comment by coolaj86** [comment]
The version field should be removed from `bower.json`. Its use is deprecated as bower uses git tags, not `bower.json.version`.

If you use `mversion patch -m`, `mversion minor -m`, and `mversion major -m` before publishing to npm, then you will always have your git tags in sync with your npm version -- and this is just a good idea anyway.

**Comment by coolaj86** [comment]
Or I'm completely wrong... because the git tags appear to be up to sync.

But I remember several versions ago getting deprecation notices about not using `bower.json.version`... weird...
