### ISSUE TITLE
Decode base64 text should ignore line breaks

### ISSUE THREAD

**Issue by J-F-Liu** [beatgammit/base64-js#31]
otherwise the decoded result is not correct or not possible.

**Comment by fanatid** [comment]
@J-F-Liu I not think that it will right.
If `base64-js` will allow ignore line breaks (btw, what you mean under line break: `\r\n` or `\n`?), why not allow ignore other symbols?

**Comment by J-F-Liu** [comment]
Long base64 text is normally split into lines, so both ignore both `\r` and `\n`, while other symbols can be considered as erroneous. See this https://en.wikipedia.org/wiki/Base64#Variants_summary_table for more details.

**Comment by feross** [comment]
FWIW, the node.js Buffer ignores invalid characters when parsing base64 encoded data. For that reason, [we do the same](https://github.com/feross/buffer/blob/master/index.js#L1565-L1566) in `feross/buffer` before passing the data to `base64-js`.

It's not clear to me whether this logic should be moved into `base64-js` or not. I have no opinion.

**Comment by compulim** [comment]
Following the latest RFC 4648 of Base64, CR/LF are forbidden. I don't think `base64-js` need to cater that scenario.

**Comment by J-F-Liu** [comment]
I think it's better to provide this by an optional parameter.

**Comment by feross** [comment]
Thanks for the feedback. We do not want to add optional parameters to this library and complicate the simple API. Closing this issue. If you want this functionality, simply strip the characters before passing to `base64-js`:

```js
var INVALID_BASE64_RE = /[^+/0-9A-Za-z-_]/g
str = str.trim().replace(INVALID_BASE64_RE, '')
base64.toByteArray(str)
```
