### ISSUE TITLE
How to use base64-js in a webbrowser

### ISSUE THREAD

**Issue by webmaster128** [beatgammit/base64-js#33]
I am having trouble to understand how to use base64-js in a webbrowser, where no require is available.

The methods `byteLength`/`toByteArray`/`fromByteArray` are not available globally when adding `<script src="js/base64-js-1.2.0/index.js"></script>` to my site.

The only hack I found to use it was to change

```
exports.byteLength = byteLength
exports.toByteArray = toByteArray
exports.fromByteArray = fromByteArray
```

into

```
var base64js_byteLength = byteLength
var base64js_toByteArray = toByteArray
var base64js_fromByteArray = fromByteArray
```

What is the itended way to do this? Could this be added to the readme? Thanks a lot!

**Comment by fanatid** [comment]
You can use browserify or file `base64js.min.js`

**Comment by webmaster128** [comment]
base64js.min.js is what I tried first before I started to change code from the lib. But how do I call e.g. toByteArray after including base64js.min.js?

**Comment by feross** [comment]
There is a global `base64js` that is added to the page that contains the exported methods:

`base64js.byteLength`, etc.
