### ISSUE TITLE
ReferenceError thrown

### ISSUE THREAD

**Issue by femiadeyemi** [beatgammit/base64-js#50]
https://github.com/beatgammit/base64-js/blob/bf68aaa277d9de7007cc0c58279c411bb10670ac/index.js#L81

https://github.com/beatgammit/base64-js/blob/bf68aaa277d9de7007cc0c58279c411bb10670ac/index.js#L82

https://github.com/beatgammit/base64-js/blob/bf68aaa277d9de7007cc0c58279c411bb10670ac/index.js#L88

https://github.com/beatgammit/base64-js/blob/bf68aaa277d9de7007cc0c58279c411bb10670ac/index.js#L89

https://github.com/beatgammit/base64-js/blob/bf68aaa277d9de7007cc0c58279c411bb10670ac/index.js#L90

These lines throw ReferenceError because `i` is not declare.

**Comment by feross** [comment]
What JS environment are you using that is throwing a `ReferenceError`?

`var` is hoisted, so this should not be a problem.

**Comment by feross** [comment]
Removed the reliance on hoisting, just to be safe.
