### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by VladimirKalachikhin** [beatgammit/base64-js#52]
ver. 1.3.0 and master.
```
<script>
var xhr = new XMLHttpRequest();
xhr.responseType = "arraybuffer";
xhr.onload = function() {
	var icon = base64js.fromByteArray(this.response); 	
	alert(icon);    // Empty string
}
xhr.open('GET', 'symbols/icon.png', true);
xhr.send();
</script>
```
What's wrong with this example?

**Comment by MoOx** [comment]
This should help you to understand what is missing.
I have to admit that doc is not really user friendly :)

https://github.com/beatgammit/base64-js/blob/bf68aaa277d9de7007cc0c58279c411bb10670ac/test/convert.js#L25
