### ISSUE TITLE
toByteArray: Indexer 'i' is not defined

### ISSUE THREAD

**Issue by sinclairzx81** [beatgammit/base64-js#54]
Hi,

Just ran this projects `index.js` file through the TypeScript compiler, and its flagged up an issue with respect to `toByteArray` function. This function is using the indexer `i` to `b64.charCodeAt(i)` but `i` is not in scope (it is used in an iteration above however).

https://github.com/beatgammit/base64-js/blob/master/index.js#L79-L93

Can be tripped if `(placeHoldersLen === 2)` or `(placeHoldersLen === 1)` evaluate `true`

**Comment by sinclairzx81** [comment]
Just a follow up, noticed it's using `var` instead of `let` (so `i` will be in scope) with the `i` value evaluated to to some value from the previous iteration. Assume this was intended. Will close.

**Comment by feross** [comment]
This is fixed now.
