### ISSUE TITLE
there is something wrong when dealing with binary datas under ie7 and below

### ISSUE THREAD

**Issue by zxuewu** [beatgammit/base64-js#55]
as the title

**Comment by zxuewu** [comment]
I found out "lookup[i] = code[i]" caused the error under ie7 and below. alert(lookup[i]) is undefined after execute "lookup[i] = code[i]" each round.

**Comment by feross** [comment]
IE7 and below do not support square bracket notation. You can try refactoring this package to use `charAt()` but this is not something that we will support directly in this package. 

You can read more here: https://stackoverflow.com/questions/5943726/string-charatx-or-stringx
