### ISSUE TITLE
base64js.toByteArray is spoliling the actual value

### ISSUE THREAD

**Issue by amartya89** [beatgammit/base64-js#57]
when a base64 encoded string is input to this function it is producing a Arraybuffer which internally changes its original value. If we again convert the array buffer to base64 then a different base64 is generated. Hence When i am trying to implement signature verification for a hybrid app, then the digest value is getting differ and hence a mismatch between front-end and back-end. 

Need an urgent help please. We are stuck at client project delivery. Earnest request.

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
