### ISSUE TITLE
version 1.5.0 can not pass uglify-js's test

### ISSUE THREAD

**Issue by yuanhaoyu** [beatgammit/base64-js#60]

**Comment by yuanhaoyu** [comment]
Hi jameson, I installed your base64-js in version 1.5.0
But I find this dist file is ES6, cannot pass uglify-js's test

**Comment by yuanhaoyu** [comment]
![image](https://user-images.githubusercontent.com/15946472/98777422-a4ae1d80-242b-11eb-88f0-b0b52a7d8238.png)

**Comment by ZxBing0066** [comment]
I have the same problem ：
```sh
ERROR in components.5e80337545f39fc02d77.js from UglifyJs
SyntaxError: Unexpected token name «i», expected punc «;» [components.5e80337545f39fc02d77.js:18544,10]
```

**Comment by pashkes** [comment]
I have the same problem, node 8.10

**Comment by OscarYin** [comment]
> I have the same problem, node 8.10

I met the same issue on node 8.16. I resolved this problem by reverting to the last version with lock file.

**Comment by pashkes** [comment]
> > I have the same problem, node 8.10
> 
> I met the same issue on node 8.16. I resolved this problem by reverting to the last version with lock file.

I can't do this because my app is building on a remote server (Circle CI)

**Comment by maiers** [comment]
Thanks everyone for the work maintaining this base library. Switching to ES6 might be worthy of publishing as a new major version though, to minimize downstream issues.

**Comment by OscarYin** [comment]
> > > I have the same problem, node 8.10
> > 
> > 
> > I met the same issue on node 8.16. I resolved this problem by reverting to the last version with lock file.
> 
> I can't do this because my app is building on a remote server (Circle CI)

we are using the jenkins build assets, and it will clone the code from a git repo, so we finally include and commit the lock file to our repo for a workaround. But I don't have any exp on Circle CI so probably not work for your case

**Comment by feross** [comment]
Released a fix as 1.5.1

**Comment by ymazhar** [comment]
version 1.5.1 still reproducing
Failed to minify the bundle. Error: static/js/vendor.a75d4fe9.js from UglifyJs
     [exec] Unexpected token name «i», expected punc «;» [static/js/vendor.a75d4fe9.js:59834,9]

**Comment by feross** [comment]
This command works for me: `browserify -s base64js -r ./ | npx uglify-js -m`

Can you confirm you're using 1.5.1 with `npm ls base64-js`?

**Comment by ymazhar** [comment]
Not all dependencies were updated (
├── base64-js@1.5.1 
├─┬ imagemin-pngquant@5.1.0
│ └─┬ pngquant-bin@4.0.0
│   └─┬ bin-build@3.0.0
│     └─┬ decompress@4.2.1
│       └─┬ decompress-tarbz2@4.1.1
│         └─┬ unbzip2-stream@1.4.3
│           └─┬ buffer@5.7.1
│             └── **base64-js@1.5.0** 
└─┬ webpack@3.11.0
  └─┬ node-libs-browser@2.2.1
    └─┬ buffer@4.9.2
      └── b**ase64-js@1.5.0**

**Comment by feross** [comment]
Great to hear. You can delete `package-lock.json` and run `npm install` to force update those dependencies.

**Comment by ymazhar** [comment]
Everything works now! Thanks
