### ISSUE TITLE
When I used it in react-native, it couldn't decode

### ISSUE THREAD

**Issue by guoyw** [beatgammit/base64-js#77]
### Description
Code
```
const base64String = 'ewogICJhIiA6ICIxIgp9';
var base64js = require('base64-js');
const arrayBuffer = base64js.toByteArray(base64String).buffer;
console.log('==============');
console.log(arrayBuffer);
console.log('==============');
```
**In React-native**
Print:
```
==============
[]
==============
```
package.json:
```
"dependencies": {
   "base64-js": "^1.5.1",
   "react": "18.2.0",
   "react-native": "0.72.4"
},
```
I am trying to create a new node project,Decode properly.
**In new project**
Print:
```
==============
ArrayBuffer {
  [Uint8Contents]: <7b 0a 20 20 22 61 22 20 3a 20 22 31 22 0a 7d>,
  byteLength: 15
}
==============
```
package.json:
```
"dependencies": {
   "base64-js": "^1.5.1"
},
```
Node:
    version: 20.5.0
### issue
I don't know what went wrong that led to this result. Is there any way to solve it?

**Comment by jonkoops** [comment]
This is a bug in React Native that has likely since been resolved. If this issue still occurs please file an issue on the [new repository](https://github.com/feross/base64-js).
